apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.premierDpltName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.premierDpltName }}
      tier: backend
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.premierDpltName }}
        tier: backend
      # timestamp used for force the redeploy each time
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
      containers:
      - name: backend
        image: {{ .Values.premierImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.premierPort }}
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.premierPort }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.premierPort }}
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.randomDpltName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.randomDpltName }}
      tier: backend
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.randomDpltName }}
        tier: backend
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
      containers:
      - name: backend
        image: {{ .Values.randomImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.randomPort }}
        env:
        - name: PREMIER-API-URL
          valueFrom:
            configMapKeyRef:
              name: configmap-data
              key: premier-api-url
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.randomPort }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.randomPort }}
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 20