apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: entry-test-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingressRulesHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.premierSvcName }}
                port:
                  number: {{ .Values.premierPort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.randomSvcName }}
                port:
                  number: {{ .Values.randomPort }}