apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.premierSvcName}}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.premierDpltName }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.premierPort }}
    nodePort: 30000
    targetPort: {{ .Values.premierPort }}
    protocol: TCP
    name: python
  selector:
    k8s-app: {{ .Values.premierDpltName }}
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.randomSvcName}}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.randomDpltName }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.randomPort }}
    nodePort: 30001
    targetPort: {{ .Values.randomPort }}
    protocol: TCP
    name: python
  selector:
    k8s-app: {{ .Values.randomDpltName }}
    tier: backend